### ISSUE TITLE
jQuery error on page load

### ISSUE THREAD

**Issue by fredmorgan** [tamw-wnet/pbs-passport-authenticate#5]
When using shortcode the button initially appears when the page loads and then disappears with the following error in the console:

Uncaught TypeError: Cannot read property 'status' of undefined
    at updateUserLoginStatusArray (jquery.pids.js?ver=0.2.5.1:120)
    at Object.success (jquery.pids.js?ver=0.2.5.1:95)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
updateUserLoginStatusArray @ jquery.pids.js?ver=0.2.5.1:120
success @ jquery.pids.js?ver=0.2.5.1:95
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
y @ jquery.js?ver=1.12.4:4
c @ jquery.js?ver=1.12.4:4
XMLHttpRequest.send (async)
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
retrievePBSLoginInfoViaAJAX @ jquery.pids.js?ver=0.2.5.1:88
checkPBSLogin @ jquery.pids.js?ver=0.2.5.1:83
(anonymous) @ jquery.pids.js?ver=0.2.5.1:243
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2

**Comment by tamw-wnet** [comment]
@fredmorgan , just to check, have you already gotten your PBS Account API keys and whitelisted your domain with PBS?

I've not used the shortcode version in some time, it's possible I need to add something to the output on the page to get everything working.  Any chance you can send around the URL for your test implementation?

**Comment by fredmorgan** [comment]
Thanks for your quick reply, @tamw-wnet.

Yes, PBS has provided credentials for both staging and production.  We currently only have it available on our staging server: https://ket.fusiondev.co/passport-plugin-test/

**Comment by tamw-wnet** [comment]
I visited 
https://ket.fusiondev.co/pbsoauth/authenticate/
and saw an error -- {"missing_arg":"laas_client_id"} -- that would make me think you need to enter your PBS Account client id and client secret in the PBS Passport Authenticate settings page.

If you have already done so, maybe there's some caching happening on certain pages that is preventing those from getting rendered?

**Comment by fredmorgan** [comment]
We were only provided with one set of credentials and entered them in the Membership Vault settings.  Are LAAS credentials required to make the plugin function?

**Comment by tamw-wnet** [comment]
Yes.  PBS account is separate from MVault.  All settings fields are required. KET will need to put in a ticket, and it will also need to include the redirect uri.  I may need to add to the documentation the details of that request.

I am out until Tuesday, but I will try and get the details together before then.

---- Fred Morgan wrote ----


We were only provided with one set of credentials and entered them in the Membership Vault settings. Are LAAS credentials required to make the plugin function?

**Comment by tamw-wnet** [comment]
@fredmorgan I've updated the README with details on getting the appropriate keypairs -- I specifically redid what is now the 'Setup and Installation' section.   That's a crucial step and it simply wasn't documented, so thanks much for bringing that to my attention.  Lemme know if there's anything I need to further clarify!

**Comment by fredmorgan** [comment]
Thanks so much, appreciate your prompt support.
