### ISSUE TITLE
Possible to get History of User after Logging In

### ISSUE THREAD

**Issue by not-original** [tamw-wnet/pbs-passport-authenticate#6]
Hi William, 

Our station was looking at a 'continue watching'  feature for logged in users.  Do you know, or have you explored, a possibility for this?

I don't think the MVault API allows for this, but I thought I would check and see if you knew of any options. 

PS: My Apologies for submitting this as an 'issue', but wasn't sure of a better way to contact you.

**Comment by tamw-wnet** [comment]
No worries!   The problem we have here is that PBS doesn't provide any way for us to access a user's preferences -- aka watchlist, or where they left off on a particular video.   They do have this available for their internal uses as part of PBS Account, but haven't made it available to 'external' developers.     

From my conversations with them I think this is on their roadmap.    Specifically they're working on an evolution of PBS Account that will also work with NPR's auth setup, and that's supposed to include 'portable' preference setting.  That's going to be at least a year, though.

If you don't need to have cross-platform access to the view status, you could try an approach that doesn't even require logging in; get the position of the video from JW Player (the basis of the Partner Player) when a person exits, store that in a cookie, and check for the cookie when a person starts up again.    I have some javascript I can dig up that checks the status of the Partner Player video iframe that you could possibly use as a starting point.

**Comment by not-original** [comment]
Thanks for the reply, really appreciate it.   I kinda came to the same conclusion, but thought I would check to see if I was missing anything -- so now I feel much better :) 

But yes, if you have that javascript, I certainly could use it.  To be honest, trying to read 'status' from the embedded iframe jwplayer video has been tricky to say the least. 

And again, thanks for the reply.

**Comment by tamw-wnet** [comment]
I use it to do event tracking.  See this blog post, you can ignore all the bits about getting Google Tag Manager working.  https://ieg.wnet.org/2015/07/using-google-tag-manager-for-custom-event-tracking/

**Comment by not-original** [comment]
Awesome, thank you very much! I owe you one!

Chet

**Comment by tamw-wnet** [comment]
that code's a few years old and there's been some updates because PBS has changed some things.

```
<script>
if(typeof window.addEventListener==='function'){
  window.addEventListener("message",receiveCOVEVideoMessage,false);
}else{
  window.attachEvent("onmessage",receiveCOVEVideoMessage);
}

var COVEVideoTitle;
var COVELastAction;
function receiveCOVEVideoMessage(evt){
  if(typeof window["dataLayer"]==='undefined'){
    dataLayer = [];
  }
  if ( evt.origin == 'http://player.pbs.org' || evt.origin == 'https://player.pbs.org' ) {
    var thissourcewindow = evt.source;
    var data=evt.data,
      action=evt.data.split('::')[0],
      value=evt.data.split('::')[1];
    if (action==="video") {
      if (value==="playing" && COVELastAction !=="seeking") {
        dataLayer.push({
          event: 'COVEEvent',
          'COVEaction':'MediaStart',
          'videoTitle': COVEVideoTitle
        });
        COVELastAction=value;
      } else if (value==="seeking") {
        COVELastAction=value;
      } else if (value==="finished" && COVELastAction !=="finished") {
        dataLayer.push({
          event: 'COVEEvent',
          'COVEaction':'MediaFinish',
          'videoTitle': COVEVideoTitle
        });
        COVELastAction=value;
      }
    } else if (action==="videoInfo") {
      videoInfo = JSON.parse(value);
      COVEVideoTitle = videoInfo.title;
      if (typeof videoInfo.program.title !== 'undefined') {
        COVEVideoTitle = videoInfo.program.title + ": " + COVEVideoTitle;
      }
    }
  }
}
</script>
```

**Comment by not-original** [comment]
Thanks, any idea what the variable for the ID or slug of the video being viewed would be?

COVEVideoID

or similar?  Is there a doc out there that lists the variables/actions?

**Comment by tamw-wnet** [comment]
not offhand.  If you dump the entire output of 'data' to console instead of what I've filtered it down to, I think it'll be there.  Probably along with the position in the video.

**Comment by not-original** [comment]
Will do, thanks again for your help!
